spring.application.name=skillswap
spring.datasource.url=jdbc:mysql://localhost:3306/skillswap_db
spring.datasource.username=root
spring.datasource.password=Gamer_yash5

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
# JWT ? use a long random Base64 string (e.g. openssl rand -base64 64)
jwt.secret=wzBMNfI8tHtNT4Zaaqjlo89M0bfMmXKtXfwlOmMyrylKGyYkmLW2bEn53fZhT9b0dCWpLK9y8CLmNJSJRz39UQ==
jwt.expiration-ms=86400000
